/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-17 13:14:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1599824644000L));
    _jspx_dependants.put("jar:file:/Users/meonji/Documents/GitRepo/onAirStudy/onAirStudy/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/meonji/Documents/GitRepo/onAirStudy/onAirStudy/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/meonji/Documents/GitRepo/onAirStudy/onAirStudy/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("<!-- 사용자작성 css -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"carouselExampleCaptions\" class=\"carousel slide\"\n");
      out.write("\tdata-ride=\"carousel\">\n");
      out.write("\t<ol class=\"carousel-indicators\">\n");
      out.write("\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"0\"\n");
      out.write("\t\t\tclass=\"active\"></li>\n");
      out.write("\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"1\"></li>\n");
      out.write("\t\t<li data-target=\"#carouselExampleCaptions\" data-slide-to=\"2\"></li>\n");
      out.write("\t</ol>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"carousel-inner\">\n");
      out.write("\t\t<div class=\"carousel-item active\">\n");
      out.write("\t\t\t <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/onlinestudy.jpg\" class=\"d-block w-50\" style=\"margin-left:640px;\" >\n");
      out.write("\t\t\t<div class=\"carousel-caption\" id=\"caption1\">\n");
      out.write("\t\t\t\t<p>Welcome</p>\n");
      out.write("\t\t\t\t<h2>onAirStudy 가</h2>\n");
      out.write("\t\t\t\t<h2>&nbsp;&nbsp;처음이신가요?</h2>\n");
      out.write("\t\t\t\t<button class=\"btn my-2 my-sm-5\" type=\"button\"\n");
      out.write("\t\t\t\t\tonclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/#';\">이용방법 안내</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/team.png\" class=\"d-block w-50\" style=\"margin-left:200px;\" >\n");
      out.write("\t\t\t<div class=\"carousel-caption\" id=\"caption2\">\n");
      out.write("\t\t\t\t<h2><strong style=\"color:#505050;\">프리미엄 가입</strong>하면</h2>\n");
      out.write("\t\t\t\t<h3>실시간 채팅이?</h3>\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/chat-bubble.png\" width=\"80px\">\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<button class=\"btn my-2 my-sm-5\" type=\"button\"\n");
      out.write("\t\t\t\t\tonclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/premium.do';\">프리미엄 혜택보기</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/test2.png\" class=\"d-block w-50\" style=\"margin-left:200px;\" >\n");
      out.write("\t\t\t<div class=\"carousel-caption\" id=\"caption3\">\n");
      out.write("\t\t\t\t<h2><strong style=\"color:#505050;\">프리미엄 가입</strong>하면</h2>\n");
      out.write("\t\t\t\t<h2>온라인 TEST</h2>\n");
      out.write("\t\t\t\t<h3>멤버들이 작성한 <strong style=\"color:#505050;\">문제풀기</strong> + <strong style=\"color:#505050;\">채점</strong>까지 ?</h3>\n");
      out.write("\t\t\t\t<button class=\"btn my-2 my-sm-5\" type=\"button\"\n");
      out.write("\t\t\t\t\tonclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/premium.do';\">프리미엄 혜택보기</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<a class=\"carousel-control-prev\" href=\"#carouselExampleCaptions\"\n");
      out.write("\t\trole=\"button\" data-slide=\"prev\"> <span\n");
      out.write("\t\tclass=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\n");
      out.write("\t\tclass=\"sr-only\">Previous</span>\n");
      out.write("\t</a> <a class=\"carousel-control-next\" href=\"#carouselExampleCaptions\"\n");
      out.write("\t\trole=\"button\" data-slide=\"next\"> <span\n");
      out.write("\t\tclass=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\n");
      out.write("\t\tclass=\"sr-only\">Next</span>\n");
      out.write("\t</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 어떤점이 좋나요? -->\n");
      out.write("<div class=\"container\">\n");
      out.write("\t<h1 class=\"text-left\" style=\"color: rgb(255, 195, 163)\">\n");
      out.write("\t\t<strong>onAir Study</strong>\n");
      out.write("\t</h1>\n");
      out.write("\t<h2>어떤 점이 좋나요?</h2>\n");
      out.write("\t<br>\n");
      out.write("\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t<img class=\"mx-auto d-block\"\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/online.png\"\n");
      out.write("\t\t\t\twidth=\"100px\">\n");
      out.write("\t\t\t<h3 class=\"text-center\">온라인상의 STUDY</h3>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5>\n");
      out.write("\t\t\t\t코로나로 인해 만나기 어려울 때, <strong>온라인에서 스터디원 모집 및 진행에 필요한 서비스 제공</strong>\n");
      out.write("\t\t\t</h5>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t<img class=\"mx-auto d-block\"\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/study.png\"\n");
      out.write("\t\t\t\twidth=\"100px\">\n");
      out.write("\t\t\t<h3 class=\"text-center\">다양한 카테고리의 스터디 그룹</h3>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5>\n");
      out.write("\t\t\t\t<strong>자격증, 면접, 컴퓨터/IT등 다양한 카테고리</strong>로 분류되어 자신의 목표에 맞는 그룹 찾기 가능\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t<img class=\"mx-auto d-block\"\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/rank.png\"\n");
      out.write("\t\t\t\twidth=\"100px\">\n");
      out.write("\t\t\t<h3 class=\"text-center\">개인/팀별로 경쟁심 자극</h3>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<h5>\n");
      out.write("\t\t\t\t자신 혹은 그룹의 <strong>출석 및 랭킹</strong>을 실시간으로 확인하면서 공부효율 높일수 있는 서비스\n");
      out.write("\t\t\t</h5>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 이달의 성실멤버 -->\n");
      out.write("<div class=\"container-fluid\" style=\"background-color: #F2EDEA; height:900px; \" >\n");
      out.write("\t<h3 class=\"text-center\">\n");
      out.write("\t\t이달의 성실멤버\n");
      out.write("\t\t</h2>\n");
      out.write("\t\t<ul class=\"list-inline\" style=\"margin:50px; \">\n");
      out.write("\t\t\t<li style=\" float: left;\">\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 이달의 성실 스터디방 -->\n");
      out.write("<div class=\"container-fluid\" style=\"background-color: #E3DBD6;  height:450px;\">\n");
      out.write("\t<h3 class=\"text-center\">\n");
      out.write("\t\t이달의 성실 스터디방\n");
      out.write("\t\t</h2>\n");
      out.write("\t\t<ul class=\"list-inline\">\n");
      out.write("\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 스터디방 리스트 -->\n");
      out.write("<div class=\"container-fluid\"\n");
      out.write("\tstyle=\"background-color: rgb(209, 203, 200); height:900px;\">\n");
      out.write("\t<h3 class=\"text-left\">\n");
      out.write("\t\t현재 모집중인 스터디\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-light\">더 보기</button>\n");
      out.write("\t\t</h2>\n");
      out.write("\t\t<br>\n");
      out.write("\n");
      out.write("\t\t<ul class=\"list-inline\">\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tstyle=\"background-color: fff; border: 4px solid rgb(247, 175, 141); border-radius: 5%; padding: 20px; width: 230px; height: 330px;\">\n");
      out.write("\t\t\t\t\t<img class=\"center-block\"\n");
      out.write("\t\t\t\t\t\tsrc=\"\"\n");
      out.write("\t\t\t\t\t\twidth=\"150px\" onclick=\"\"> \n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/heart.png\"\n");
      out.write("\t\t\t\t\t\t\t width=\"20px\"></a> <br>\n");
      out.write("\t\t\t\t\t<h5 class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t방 제목<a href=\"#\" onclick=\"\"></a>\n");
      out.write("\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t<h5 class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t리더 아이디<a href=\"#\" onclick=\"\"></a>\n");
      out.write("\t\t\t\t\t\t</h4>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-inline\">\n");
      out.write("\t\t\t\t\t\t\t<li><button type=\"button\" class=\"btn btn-light\">둘러보기</button></li>\n");
      out.write("\t\t\t\t\t\t\t<li><button type=\"button\" class=\"btn btn-light\">신청하기</button></li>\n");
      out.write("\t\t\t\t\t\t\t<li><button type=\"button\" class=\"btn btn-danger\">신고하기</button></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /index.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /index.jsp(135,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(135,3) '${ list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /index.jsp(135,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("member");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\n");
            out.write("\t\t\t\t\t<div\n");
            out.write("\t\t\t\t\t\tstyle=\"background-color: fff; border: 4px solid rgb(247, 175, 141); border-radius: 5%; padding: 20px; width: 230px; height: 330px;\">\n");
            out.write("\t\t\t\t\t\t<img class=\"center-block\"\n");
            out.write("\t\t\t\t\t\t\tsrc=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("\t\t\t\t\t\t\twidth=\"150px\" onclick=\"\">\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t<h4 class=\"text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<a href=\"#\"\n");
            out.write("\t\t\t\t\t\t\t\tonclick=\"\"></a>\n");
            out.write("\t\t\t\t\t\t</h4>\n");
            out.write("\t\t\t\t\t\t<h5 class=\"text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.memberName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<a href=\"#\"\n");
            out.write("\t\t\t\t\t\t\t\tonclick=\"\"></a>\n");
            out.write("\t\t\t\t\t\t</h5>\n");
            out.write("\t\t\t\t\t\t<h5 class=\"text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.comment }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<a href=\"#\"\n");
            out.write("\t\t\t\t\t\t\t\tonclick=\"\"></a>\n");
            out.write("\t\t\t\t\t\t</h5>\n");
            out.write("\t\t\t\t\t\t<h5 class=\"text-center\">성실도 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.diligentPoint }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("점<a href=\"#\"\n");
            out.write("\t\t\t\t\t\t\t\tonclick=\"\"></a>\n");
            out.write("\t\t\t\t\t\t</h5>\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
